# Generated by Django 5.2.6 on 2025-09-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='We Build Software That Works', max_length=200)),
                ('hero_subtitle', models.CharField(default='Websites • Mobile Apps • Custom Software', max_length=200)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('accent_color', models.CharField(default='#ffc107', max_length=7)),
            ],
        ),
    ]
