# Generated by Django 5.2.6 on 2025-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesetting_delete_portfolioitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='title',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(default='Mirpur, Dhaka, Bangladesh'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(default='info@softnext.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_description',
            field=models.TextField(default='We create custom software solutions that drive growth, innovation, and success for businesses worldwide.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Transform Your Ideas Into Digital Reality', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(default='+880 1627457073', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='SoftNext', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/logo/'),
        ),
    ]
